UPDATE perk
SET code = UPPER(code);

ALTER TABLE damage_type
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE damage_type
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE damage_type
    ADD COLUMN image_path VARCHAR(512) NULL;