services:
  # Base de données ATF
  apocalypse_the_fall_db:
    image: postgis/postgis:17-3.4
    container_name: apocalypse_the_fall_db
    restart: always
    environment:
      POSTGRES_DB: apocalypse_the_fall_db
      POSTGRES_USER: apocalypse_the_fall_user
      POSTGRES_PASSWORD: apocalypse_the_fall_pass
    ports:
      - "5432:5432"
    volumes:
      - apocalypse_the_fall_data:/var/lib/postgresql/data

  # Base de données Keycloak
  keycloak_db:
    image: postgres:17
    container_name: keycloak_db
    restart: always
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_pass
    ports:
      - "5433:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  # Zookeeper (nécessaire pour Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_pass
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    depends_on:
      - keycloak_db

volumes:
  postgres_data:
    driver: local
  apocalypse_the_fall_data:
    driver: local
  keycloak_data:
    driver: local
