server:
  port: 8080

spring:
  application:
    name: Apocalypse The Fall

  ai:
    openai:
      api-key: "sk-xxxxxx"  # TODO Remplacer "sk-xxxxxx" par clé API

  datasource:
    url: jdbc:postgresql://localhost:5432/apocalypse_the_fall_db
    username: apocalypse_the_fall_user
    password: apocalypse_the_fall_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    #show-sql: true
    properties:
      hibernate:
      #format_sql: true
      #generate_statistics: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: apocalypse-the-fall-game-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.apocalypse.thefall.event

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/atf

# Configuration des topics Kafka pour le jeu
kafka:
  topics:
    player-movement: player-movement

# Configuration du jeu
game:
  inventory:
    base-weight-capacity: 150
    weight-per-strength: 10
    action-points:
      equip: 1
      unequip: 1
      reload: 2
      unload: 1

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.hibernate.SQL: DEBUG