server:
  port: 8080

spring:
  application:
    name: Apocalypse The Fall

  ai:
    openai:
      api-key: "sk-xxxxxx"  # TODO replace "sk-xxxxxx" by API key

  datasource:
    url: jdbc:postgresql://localhost:5432/apocalypse_the_fall_db
    username: apocalypse_the_fall_user
    password: apocalypse_the_fall_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #show-sql: true
    properties:
      hibernate:
        cache.use_second_level_cache: true
        cache.use_query_cache: true
        cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax.cache.provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
        default_batch_fetch_size: 64
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        javax.cache.missing_cache_strategy: create
        generate_statistics: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: apocalypse-the-fall-game-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.apocalypse.thefall.event

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/atf

# Kafka conf
kafka:
  topics:
    player-movement: player-movement

# Game conf
game:
  inventory:
    base-weight-capacity: 150
    weight-per-strength: 10
    action-points:
      equip: 1
      unequip: 1
      reload: 2
      unload: 1

cache:
  logging:
    enabled: true

logging:
  level:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: OFF
    org.apache.kafka.clients.producer.ProducerConfig: OFF
    org.apache.kafka.clients.admin.AdminClientConfig: OFF
#   org.springframework.security: DEBUG
#   org.springframework.security.oauth2: DEBUG
#   org.hibernate.SQL: DEBUG